apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: tc-real-targets
  labels:
    app.kubernetes.io/name: directus
    app.kubernetes.io/part-of: tool-compiler
    tool-compiler.io/protocol: graphql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: directus
  ports:
    - name: http
      port: 8055
      targetPort: 8055
      protocol: TCP
