apiVersion: v1
kind: Service
metadata:
  name: aria2
  namespace: example-targets
  labels:
    app.kubernetes.io/name: aria2
    app.kubernetes.io/part-of: tool-compiler
    tool-compiler.io/protocol: jsonrpc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aria2
  ports:
    - name: jsonrpc
      port: 6800
      targetPort: 6800
      protocol: TCP
