apiVersion: v1
kind: Service
metadata:
  name: soap-server
  namespace: example-test-targets
  labels:
    app: soap-server
    app.kubernetes.io/name: soap-server
    app.kubernetes.io/part-of: example-test-targets
    app.kubernetes.io/component: test-target
    tool-compiler.io/protocol: soap
spec:
  type: ClusterIP
  selector:
    app: soap-server
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
