apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: tool-compiler-test-targets
  labels:
    app: grpc-server
    tool-compiler.io/protocol: grpc
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
