apiVersion: v1
kind: Service
metadata:
  name: soap-cxf
  namespace: example-targets
  labels:
    app.kubernetes.io/name: soap-cxf
    app.kubernetes.io/part-of: tool-compiler
    tool-compiler.io/protocol: soap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: soap-cxf
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
