apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tool-compiler.fullname" . }}-secrets
  labels:
    {{- include "tool-compiler.commonLabels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.global.database.password | b64enc | quote }}
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
  billing-secret: {{ .Values.global.billingSecret | b64enc | quote }}
