"""LLM-driven seed mutation for REST endpoint discovery (RESTSpecIT-style).

Uses an LLM to generate candidate endpoint paths based on already-discovered
endpoints, then validates them via HTTP probing (OPTIONS/GET).  This implements
the RESTSpecIT paper's insight that LLMs can infer API naming conventions and
guess plausible routes from observed patterns.

Activation: pass an ``LLMClient`` to ``generate_seed_candidates()``.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Protocol

logger = logging.getLogger(__name__)


class SeedMutationLLMClient(Protocol):
    """Minimal LLM interface for seed mutation — matches enhancer.LLMClient."""

    def complete(self, prompt: str, max_tokens: int = 4096) -> Any: ...


@dataclass(frozen=True)
class SeedCandidate:
    """A candidate endpoint path generated by the LLM."""

    path: str
    methods: tuple[str, ...]
    rationale: str
    confidence: float


@dataclass
class SeedMutationResult:
    """Result of an LLM seed mutation round."""

    candidates_generated: int = 0
    candidates_validated: int = 0
    candidates_accepted: int = 0
    new_paths: list[str] = field(default_factory=list)


SEED_MUTATION_PROMPT = """\
You are an API endpoint discovery expert. Given the following discovered REST API \
endpoints, generate additional endpoint paths that likely exist based on common \
REST API patterns and naming conventions.

Rules:
1. Analyze the naming patterns, resource hierarchy, and HTTP methods of discovered endpoints.
2. Generate plausible NEW endpoints that follow the same conventions.
3. Consider: CRUD completions, sub-resources, search/filter endpoints, bulk operations, \
   status endpoints, and admin/config paths.
4. Do NOT repeat endpoints that are already discovered.
5. Return ONLY valid JSON. No markdown, no explanation.
6. Each candidate should have a confidence score (0.0-1.0) based on how likely it exists.

Base URL: {base_url}

Discovered endpoints:
{discovered_json}

Return JSON array:
[
  {{
    "path": "/api/example/new-path",
    "methods": ["GET", "POST"],
    "rationale": "Brief explanation of why this endpoint likely exists",
    "confidence": 0.75
  }}
]
"""


def generate_seed_candidates(
    *,
    llm_client: SeedMutationLLMClient,
    base_url: str,
    discovered_paths: list[dict[str, Any]],
    max_candidates: int = 30,
) -> list[SeedCandidate]:
    """Use LLM to generate candidate endpoint paths from discovered ones.

    Parameters
    ----------
    llm_client:
        LLM client implementing the ``complete(prompt, max_tokens)`` protocol.
    base_url:
        The API base URL being explored.
    discovered_paths:
        List of dicts with ``path`` and ``methods`` keys describing already-discovered endpoints.
    max_candidates:
        Maximum number of candidates to return.

    Returns
    -------
    list[SeedCandidate]
        Validated candidate paths sorted by confidence (descending).
    """
    if not discovered_paths:
        return []

    discovered_json = json.dumps(discovered_paths, indent=2)
    prompt = SEED_MUTATION_PROMPT.format(
        base_url=base_url,
        discovered_json=discovered_json,
    )

    try:
        response = llm_client.complete(prompt, max_tokens=4096)
        content = response.content if hasattr(response, "content") else str(response)
    except Exception:
        logger.warning("LLM seed mutation call failed", exc_info=True)
        return []

    candidates = _parse_seed_response(content)

    # Filter out already-discovered paths
    discovered_path_set = {d["path"] for d in discovered_paths}
    candidates = [c for c in candidates if c.path not in discovered_path_set]

    # Sort by confidence and limit
    candidates.sort(key=lambda c: c.confidence, reverse=True)
    return candidates[:max_candidates]


def _parse_seed_response(content: str) -> list[SeedCandidate]:
    """Parse LLM JSON response into SeedCandidate list."""
    try:
        text = content.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            if lines[-1].strip() == "```":
                text = "\n".join(lines[1:-1])
            else:
                text = "\n".join(lines[1:])
            text = text.strip()

        data = json.loads(text)
        if not isinstance(data, list):
            logger.warning("LLM seed response is not a JSON array")
            return []

        candidates: list[SeedCandidate] = []
        for item in data:
            path = item.get("path", "")
            if not path or not isinstance(path, str):
                continue
            methods = tuple(
                m.upper()
                for m in item.get("methods", ["GET"])
                if isinstance(m, str)
            )
            if not methods:
                methods = ("GET",)
            candidates.append(
                SeedCandidate(
                    path=path,
                    methods=methods,
                    rationale=item.get("rationale", ""),
                    confidence=float(item.get("confidence", 0.5)),
                )
            )
        return candidates
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        logger.warning("Failed to parse LLM seed mutation response", exc_info=True)
        return []
