apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  namespace: tc-real-targets
  labels:
    app.kubernetes.io/name: pocketbase
    app.kubernetes.io/part-of: tool-compiler
    tool-compiler.io/protocol: rest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pocketbase
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
